# Generated by Django 4.2.6 on 2024-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="archived",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("expertise", "Expertise"),
                    ("contentbeheer", "Contentbeheer"),
                    ("notificeren", "Notificeren"),
                    ("archived", "Archived"),
                ],
                default="expertise",
                max_length=20,
            ),
        ),
    ]
