# Generated by Django 4.2.6 on 2024-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_remove_task_archived_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("expertise", "Expertise"),
                    ("contentbeheer", "Contentbeheer"),
                    ("notificeren", "Notificeren"),
                ],
                default="expertise",
                max_length=20,
            ),
        ),
    ]
