# Generated by Django 4.2.6 on 2024-11-06 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_task_archived_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="column_status",
            field=models.CharField(
                choices=[
                    ("expertise", "Expertise"),
                    ("contentbeheer", "Contentbeheer"),
                    ("notificeren", "Notificeren"),
                ],
                default="expertise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="coverages",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("technology", "Technology"),
                    ("finance", "Finance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("todo", "To Do"), ("doing", "Doing")],
                default="todo",
                max_length=10,
            ),
        ),
    ]
