# Generated by Django 4.2.6 on 2024-11-06 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_task_description_remove_task_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="column_status",
            new_name="column",
        ),
    ]
