# Generated by Django 4.2.6 on 2024-11-29 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0007_task_priority_alter_task_country_alter_task_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sector",
            field=models.CharField(
                choices=[
                    ("aardappelen", "Aardappelen"),
                    ("bloembollen", "Bloembollen"),
                    ("divers", "Diverse Producten"),
                    ("groenteenfruit", "Groente en Fruit"),
                    ("plantuien", "Plantuien, Sjalotten, Knoflook"),
                    ("sierteelt", "Sierteelt, Boomkwekerij en Fruitgewassen"),
                    ("zaaizaden", "Zaaizaden"),
                ],
                default="zaaizaden",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
