# Generated by Django 4.2.6 on 2024-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_sector_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Aardappelen", "Aardappelen"),
                    ("Bloembollen", "Bloembollen"),
                    ("Diverse Producten", "Diverse Producten"),
                    ("Groente en Fruit", "Groente en Fruit"),
                    (
                        "Plantuien, Sjalotten, Knoflook",
                        "Plantuien, Sjalotten, Knoflook",
                    ),
                    (
                        "Sierteelt, Boomkwekerij en Fruitgewassen",
                        "Sierteelt, Boomkwekerij en Fruitgewassen",
                    ),
                    ("Zaaizaden", "Zaaizaden"),
                ],
                default="Zaaizaden",
                max_length=40,
            ),
        ),
    ]
