# Generated by Django 4.2.6 on 2024-11-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_task_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
