# Generated by Django 4.2.6 on 2024-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Aardappelen", "Aardappelen"),
                    ("Bloembollen", "Bloembollen"),
                    ("Diverse Producten", "Diverse Producten"),
                    ("Groente en Fruit", "Groente en Fruit"),
                    ("Plantuien", "Plantuien"),
                    ("Sierteelt", "Sierteelt"),
                    ("Zaaizaden", "Zaaizaden"),
                ],
                default="Zaaizaden",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Te Doen", "Te Doen"),
                    ("Mee Bezig", "Mee Bezig"),
                    ("In Afwachting", "In Afwachting"),
                ],
                default="Te Doen",
                max_length=15,
            ),
        ),
    ]
