# Generated by Django 4.2.6 on 2024-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_alter_task_sector_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Hoog", "Hoog"),
                    ("Gemiddeld", "Gemiddeld"),
                    ("Laag", "Laag"),
                ],
                default="Gemiddeld",
                max_length=10,
            ),
        ),
    ]
