# Generated by Django 4.2.6 on 2024-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_archived",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(default="Temporary", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or details about the task."
            ),
        ),
    ]
